# Generated by Django 4.1.4 on 2023-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=10, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=20, verbose_name='Teacher Name'),
        ),
    ]
